[build]
  command = ""
  functions = "netlify/functions"
  publish = "."


[functions]
  directory = "netlify/functions"

[[scheduled]]
  path = "/.netlify/functions/cleanup-expired-sessions"
  schedule = "0 * * * *"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL"
  SECRETS_SCAN_OMIT_VALUES = "https://dvsruqzfdzjyahknixmk.supabase.co"

