[[functions]]
  function = "cleanup-expired-sessions"
  schedule = "0 * * * *"
  generator = "edge"
  included_files = ["netlify/edge-functions/cleanup-expired-sessions.js"]
[build]
  command = ""
  functions = "netlify/functions"
  publish = "."

[functions]
  directory = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL"
  SECRETS_SCAN_OMIT_VALUES = "https://dvsruqzfdzjyahknixmk.supabase.co"

